# Generated by Django 2.2.11 on 2020-03-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconfig',
            name='bridgeExternal_interfaces',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='bridgeHwaddr',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='bridgeMode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='bridgeMtu',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='dnsDomain',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='dnsMode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='fanOverlay_subnet',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='fanType',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='fanUnderlay_subnet',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Dhcp',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4DhcpExpiry',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4DhcpGateway',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4DhcpRanges',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Firewall',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Nat',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4NatAddress',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4NatOrder',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Routes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Routing',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Dhcp',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6DhcpExpiry',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6DhcpGateway',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6DhcpRanges',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Firewall',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Nat',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6NatAddress',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6NatOrder',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Routes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Routing',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='rawDnsMasq',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMEGroup',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMEInterface',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMELocal',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMEPort',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMEProtocol',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMERemote',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMETTL',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
