# Generated by Django 2.2.11 on 2020-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comex', '0003_auto_20200323_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconfig',
            name='bridgeMode',
            field=models.CharField(default='lord', max_length=30),
        ),
    ]
