# Generated by Django 2.2.11 on 2020-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comex', '0004_auto_20200323_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkconfig',
            name='ipv6DhcpGateway',
        ),
        migrations.RemoveField(
            model_name='networkconfig',
            name='ipv6DhcpRanges',
        ),
        migrations.AddField(
            model_name='networkconfig',
            name='ipv6DhcpStateful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='bridgeDriver',
            field=models.CharField(default='native', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='bridgeMode',
            field=models.CharField(default='standard', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='bridgeMtu',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='dnsDomain',
            field=models.CharField(default='lxd', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='dnsMode',
            field=models.CharField(default='managed', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='fanOverlay_subnet',
            field=models.CharField(default='240.0.0.0/8', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='fanType',
            field=models.CharField(default='vxlan', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Dhcp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4DhcpExpiry',
            field=models.CharField(default='1h', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Firewall',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Nat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4NatAddress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4NatOrder',
            field=models.CharField(default='before', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Routes',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv4Routing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Dhcp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6DhcpExpiry',
            field=models.CharField(default='1h', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Firewall',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Nat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6NatOrder',
            field=models.CharField(default='before', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='ipv6Routing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMEGroup',
            field=models.CharField(default='239.0.0.1', max_length=30),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMEId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMEPort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networkconfig',
            name='tunnelNAMETTL',
            field=models.IntegerField(default=1),
        ),
    ]
