# Generated by Django 2.2.11 on 2020-03-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comex', '0006_auto_20200323_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='networkConfig',
        ),
    ]
